#!/usr/bin/env bash
set -euo pipefail

# lndgのpre-startを参考に作った
# App directory is one level up from this script
APP_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)"
APP_DATA_DIR="${APP_DIR}/data/pgAdmin"
DESIRED_OWNER="5050:5050"

set_correct_permissions() {
    local -r path="${1}"

    if [[ -d "${path}" ]]; then
        owner=$(stat -c "%u:%g" "${path}")

        if [[ "${owner}" != "${DESIRED_OWNER}" ]]; then
            chown -R "${DESIRED_OWNER}" "${path}"
        fi
    fi
}

create_directory_if_not_exists() {
    local -r dir="${1}"
    if [[ ! -d "${dir}" ]]; then
        mkdir -p "${dir}"
        set_correct_permissions "${dir}"
    fi
}


# Create directories if they don't exist
create_directory_if_not_exists "${APP_DATA_DIR}"
